version: '3.1'

services:
  api:
    container_name: user-manager
    image: user-manager:1.0.0
    expose:
      - 8090
    ports:
      - "8090:8090"
    environment:
      TZ: "America/Sao_Paulo"

networks:
  default:
    external:
      name: microservices